apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-notary.fullname" . }}
  labels:
{{ include "kube-notary.labels" . | indent 4 }}
data:
  config.yaml: |-
    log:
      level: {{ .Values.log.level }}
    watch:
      namespace: {{ .Values.watch.namespace }}
      interval: {{ .Values.watch.interval }}
    trust:
      org: {{ .Values.trust.org }}
      keys:
        {{- range .Values.trust.keys }}
        - {{ . | quote }}
        {{- end }}
    cnlc:
      host: {{ .Values.cnlc.host }}
      port: {{ .Values.cnlc.port }}
      cert: {{ .Values.cnlc.cert }}
      noTls: {{ .Values.cnlc.noTls }}
      skipTlsVerify: {{ .Values.cnlc.skipTlsVerify }}
      crossLedgerKeyLedgerName: {{ .Values.cnlc.crossLedgerKeyLedgerName }}
      signerID: {{ .Values.cnlc.signerID }}
