apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-notary.fullname" . }}
  labels:
{{ include "kube-notary.labels" . | indent 4 }}
data:
  config.yaml: |-
    log:
      level: {{ .Values.LOG_LEVEL }}
    watch:
      namespace: {{ .Values.WATCH_NAMESPACE }}
      interval: {{ .Values.WATCH_INTERVAL }}
    trust:
      org: {{ .Values.TRUST_ORG }}
      keys:
        {{- range .Values.TRUST_KEYS }}
        - {{ . | quote }}
        {{- end }}
    cnc:
      host: {{ .Values.CNC_HOST }}
      port: {{ .Values.CNC_PORT }}
      cert: {{ .Values.CNC_CERT }}
      noTls: {{ .Values.CNC_NO_TLS }}
      skipTlsVerify: {{ .Values.CNC_SKIP_TLS_VERIFY }}
      crossLedgerKeyLedgerName: {{ .Values.CNC_CROSS_LEDGER_KEY_LEDGER_NAME }}
      signerID: {{ .Values.CNC_SIGNER_ID }}
