apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-notary.fullname" . }}
  labels:
{{ include "kube-notary.labels" . | indent 4 }}
data:
  config.yaml: |-
    log:
      level: {{ .Values.log.level }}
    watch:
      namespace: {{ .Values.watch.namespace }}
      interval: {{ .Values.watch.interval }}
    trust:
      org: {{ .Values.trust.org }}
      keys:
        {{- range .Values.trust.keys }}
        - {{ . | quote }}
        {{- end }}
    cnc:
      host: {{ .Values.cnc.host }}
      port: {{ .Values.cnc.port }}
      cert: {{ .Values.cnc.cert }}
      noTls: {{ .Values.cnc.noTls }}
      skipTlsVerify: {{ .Values.cnc.skipTlsVerify }}
      crossLedgerKeyLedgerName: {{ .Values.cnc.ledgerName }}
      signerID: {{ .Values.cnc.signerID }}
