apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-notary.fullname" . }}
  labels:
{{ include "kube-notary.labels" . | indent 4 }}
    k8s-app: kube-notary
type: Opaque
data:
  api-key: {{ required "Please specify the api key" .Values.cnc.apiKey | b64enc }}
