{
 "title": "Kubernetes CodeNotary vcn Overview",
 "description": "This dashboard shows the running Kubernetes (docker container platform) container verification status based on CodeNotary.io results.",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "Container",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "kube_notary_total_listed_pods" }
   ]
  },
  {
   "title": "Status Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Container" }
   ],
   "targets": [
    {
     "expr": "count(vcn_verification_status==0)",
     "legendFormat": "Trusted"
    },
    {
     "expr": "count(vcn_verification_status==2)",
     "legendFormat": "Unknown"
    },
    {
     "expr": "count(vcn_verification_status==1)",
     "legendFormat": "Untrusted"
    },
    {
     "expr": "count(vcn_verification_status==3)",
     "legendFormat": "Unsupported"
    }
   ]
  },
  {
   "title": "Verifiable",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vcn_verification_level>0)"
    }
   ]
  },
  {
   "title": "Not verifiable",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vcn_verification_level==0)"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "vcn_verification_status+0" },
    { "expr": "vcn_verification_level+0" }
   ]
  }
 ]
}