{
 "title": "Kubernetes CodeNotary",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "All container",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(vcn_verification_level)" }
   ]
  },
  {
   "title": "Trusted Container",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vcn_verification_status==0)"
    }
   ]
  },
  {
   "title": "Verifiable Container",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(vcn_verification_level>0)"
    }
   ]
  },
  {
   "title": "Not verifiable Container",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(vcn_verification_level==0)"
    }
   ]
  },
  {
   "title": "Untrusted Container",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(vcn_verification_status==1)"
    }
   ]
  },
  {
   "title": "Unsupported Container",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(vcn_verification_status==3)"
    }
   ]
  },
  {
   "title": "Unknown Container",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(vcn_verification_status==2)"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "vcn_verification_status" }
   ]
  }
 ]
}