---
# Source: kube-notary/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-notary
  labels:
    app.kubernetes.io/name: kube-notary
    app.kubernetes.io/instance: kube-notary
data:
  config.yaml: |-
    log:
      level: debug
    watch:
      namespace:
      interval: 60s
    trust:
      org:
      keys:
    cnlc:
      host:
      port: 3324
      cert:
      noTls: true
      skipTlsVerify: false
      crossLedgerKeyLedgerName:
      signerID:
